---

- name: Install dependencies
  apt: name={{ item }} state=installed update_cache=yes
  become: yes
  become_user: root
  with_items:
    - build-essential
    - python-dev
    - libbz2-dev
  when: ansible_os_family == "Debian"

- name: Install dependencies
  yum: name={{ item }} state=latest
  become: yes
  become_user: root
  with_items:
    - bzip2
    - python-devel
    - gcc
    - gcc-c++
    - kernel-devel
    - bzip2-devel
  when: ansible_os_family == "RedHat"

- name: Create work directory
  file: path={{ boost_work_dir }} state=directory

- name: Create install directory
  become: yes
  become_user: root
  file: path={{ boost_prefix }} state=directory
  when: boost_prefix is defined

# Boost's official release was hosted on sourceforge, which is very unstable. So
# we clone it directly from github.
- name: Get boost source
  git: repo=https://github.com/boostorg/boost.git
       dest='{{ boost_work_dir }}'
       version='boost-{{ boost_version }}'

- name: Bootstrap Boost
  command: chdir={{ boost_work_dir }} {{ cc_prefix }} ./bootstrap.sh
  when: boost_prefix is not defined

- name: Bootstrap Boost
  command: chdir={{ boost_work_dir }} {{ cc_prefix }} "./bootstrap.sh --prefix={{ boost_prefix }}"
  when: boost_prefix is defined

- name: Make Headers
  command: chdir={{ boost_work_dir }} {{ cc_prefix }} "./b2 headers"

- name: Make Boost
  command: chdir={{ boost_work_dir }} {{ cc_prefix }} "./b2 variant=release -j6"
  when: boost_fpic is not defined or boost_fpic != True

- name: Make Boost with fPIC
  command: chdir={{ boost_work_dir }} {{ cc_prefix }} "./b2 cxxflags=-fPIC cflags=-fPIC variant=release -j6"
  when: boost_fpic == True

- name: Insall Boost
  become: yes
  become_user: root
  command: chdir={{ boost_work_dir }} ./b2 install
